image_preprocess_node:
  ros__parameters:
    eo_image_topic: /camera/eo
    eo_frame_info_topic: /camera/eo/frame_info

    eo_output_topic: /video/eo/preprocessed
    eo_output_frame_info_topic: /video/eo/preprocessed/frame_info

    sync_queue_size: 30
    eo_width: 1280
    eo_height: 720
    enable_calibration: true
    eo_flip_vertical: false
    calibration_width: 1280
    calibration_height: 720

    camera_fx: 977.871299
    camera_fy: 973.856636
    camera_cx: 594.894793
    camera_cy: 301.901165
    dist_coeffs: [-0.396147, 0.327762, 0.013861, 0.011281, -0.350658]
    latency_log_path: "/ros2_ws/log/latency_image_preprocess.csv"
    latency_log_every_n: 1
