yolo_detector_eo_drone_node:
  ros__parameters:
    model_path: "/ros2_ws/src/yolo_detector_pkg/model/best2.pt"
    image_topic: "/video/eo/preprocessed"
    frame_info_topic: "/video/eo/preprocessed/frame_info"
    detection_topic: "/detections/eo/drone"
    conf_threshold: 0.25
    iou_threshold: 0.45
    imgsz: 640
    device: "0"
    half: true
    max_det: 300
    enabled: true
    publish_empty: true
    image_queue_size: 1
    log_period_sec: 2.0
    frame_info_cache_size: 60
    allowed_class_ids: "1"
    class_filter: ""
    secondary_model_path: ""
    secondary_allowed_class_ids: ""
    secondary_class_filter: ""
    secondary_conf_threshold: -1.0
    secondary_output_class_id: -1
    secondary_output_class_name: ""
    dual_model_mode: "sequential"
    process_every_n_frames: 1
    latency_log_path: "/ros2_ws/log/latency_yolo_eo_drone.csv"
    latency_log_every_n: 1
