yolo_detector_node:
  ros__parameters:
    model_path: "/home/lig/models/best.onnx"
    image_topic: "/video/raw"
    score_threshold: 0.25
    nms_threshold: 0.45
    input_width: 640
    input_height: 640
    enable_at_start: true
    inference_period_ms: 1
    class_names: ["person"]