video_rx_node2:
  ros__parameters:
    eo_device: "/dev/video0"
    eo_io_mode: 0
    eo_width: 1280
    eo_height: 720
    eo_fps: 60
    eo_publish_topic: "/camera/eo"
    eo_frame_info_topic: "/camera/eo/frame_info"
    eo_source_name: "capturecard_eo"
    eo_frame_id: "camera_eo"

    ir_udp_port: 5001
    ir_camera_id: 2
    ir_width: 640
    ir_height: 480
    ir_fps: 10.0
    ir_publish_topic: "/camera/ir"
    ir_frame_info_topic: "/camera/ir/frame_info"
    ir_source_name: "jetson_udp_ir"
    ir_frame_id: "camera_ir"
    ir_rotate_ccw_90: true

    stale_ms: 2000
